apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/haihuynh2002/catalog-service/k8s?ref=8ad18b95fda3c59df888d6411492881e2d63c670

patches:
- path: patch-env.yml
- path: patch-resources.yml
- path: patch-volumes.yml

configMapGenerator:
- behavior: merge
  files:
  - application-prod.yml
  name: catalog-config
images:
- name: catalog-service
  newName: ghcr.io/haihuynh2002/catalog-service
  newTag: 8ad18b95fda3c59df888d6411492881e2d63c670

replicas:
- count: 2
  name: catalog-service
